language: node_js
dist: xenial
node_js:
  - "12"
before_install:
  - mkdir demo
  - printf '{"username":"fj","password":"fjkd"}' > demo/x.h5
script:
  - npm test
after_success:
  - nyc report --reporter=text-lcov | coveralls
